language: julia

julia:
  - 0.7
  - 1.0
os:
  - linux
  - osx

notifications:
  email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Schemata"); Pkg.test("Schemata"; coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(dirname(dirname(pathof(Schemata)))); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
